version: "3"
services:
  web:
    image: umanchanda/umanchandastocks:umanchandastocks
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: