services:
  - type: web
    name: umanchandastocks
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run gunicorn src.application:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
